ID holds value after wifi misconfiguration
ElectronicCats/BomberCat pull request #27
Opened 2024-06-26 21:05 UTC by REGIOIGER

The client or host no longer loses connection with the MQTT server when the BomberCat WiFi is incorrectly configured.
The test_host function is also added to test that there is communication with the MQTT server and response from the NFC card.

2024-06-26 21:50 UTC, sabas1080 requested changes

2024-06-26 21:50 UTC, sabas1080 commented on firmware/host_Relay_NFC/host_Relay_NFC.ino
> +    Serial.println("entró a publicar...");
Manten los comentarios en ingles por favor

2024-06-26 21:50 UTC, sabas1080 commented on firmware/host_Relay_NFC/host_Relay_NFC.ino
> +  //delay(500);
Este comentario es necesario?

2024-06-28 15:37 UTC, REGIOIGER commented on firmware/host_Relay_NFC/host_Relay_NFC.ino
> +  //delay(500);
Se removieron comentarios innecesarios

2024-06-28 16:23 UTC, sabas1080 approved these changes

2024-07-17 15:41 UTC, merged